apiVersion: v1
kind: PersistentVolume            
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: standard      
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:                       
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain  
---    
apiVersion: v1
kind: PersistentVolumeClaim        
metadata:                          
  name: mysql-pv-claim
  labels:
    app: demo-app
spec:                              
  storageClassName: standard       
  accessModes:
    - ReadWriteOnce                
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1                    
kind: Service                     
metadata:
  name: demo-app-mysql         
  labels:                         
    app: demo-app
spec:
  ports:
    - port: 3306
  selector:                       
    app: demo-app
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment                    
metadata:
  name: demo-app-mysql           
  labels:                           
    app: demo-app
spec:
  selector:
    matchLabels:                    
      app: demo-app
      tier: mysql
  strategy:
    type: Recreate
  template:                         
    metadata:
      labels:                       
        app: demo-app
        tier: mysql
    spec:                           
      containers:
      - image: mysql:5.6            
        name: mysql
        env:                        
        - name: MYSQL_ROOT_PASSWORD 
          value: R00t
        - name: MYSQL_DATABASE
          value: polls
        - name: MYSQL_USER
          value: callicoder
        - name: MYSQL_PASSWORD
          value: c@ll1c0d3r
        ports:
        - containerPort: 3306        
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage  
          mountPath: /var/lib/mysql
      volumes:                       
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
